### ISSUE TITLE
Valores de items en lineas de pago

### ISSUE THREAD

**Issue by miguel-molinari** [ingadhoc/account-payment#117]
Impacted versions:
 
 - 11.0
 
Steps to reproduce:
 
 1. crear nuevo pago a proveedor (Facturación | Compras | Pagos a Proveedor)
 2. el proveedor debe posee deuda (por ejemplo, $450)
 3. crear una nueva linea de pago
 4. modificar el campo Cantidad a Pagar por $50.
 5. Guardar linea de pago
 
Current behavior:
 
 - En la linea de pago se visualiza en el importe de Pago $450 
 
Expected behavior:
 
 - En la linea de pago se debería visualizar en el importe ingresado de $50

**Comment by jjscarafia** [comment]
Buenas, gracias por el reporte. Si, estamos al tanto de la situación pero por un tema de framework de odoo no encontramos solución por el momento. Si se utiliza el botón guardar y luego se agrega línea, en ves de "guardar y nueva línea", debería llevar bien el saldo.
Dejo abierto el ticket, bienvenido un PR para resolverlo
