### ISSUE TITLE
Ingreso de Nueva Linea de pago

### ISSUE THREAD

**Issue by miguel-molinari** [ingadhoc/account-payment#118]
Impacted versions:
 
 - 11.0 (CE)
 
Steps to reproduce:
 
 1. Ingresar al modulo de Subscripciones
 2. Visualizar una subscripcion
 3. Ingresar a las facturas realacionadas
 4. Presionar el boton de registrar pago.
 5. Se visualizar el form para ingresar un pago.
 
Current behavior:
 
 - En la linea de pago no se visualiza el link para "Añadir un elemento"
 
Expected behavior:
 
 - Visualizar el link para "Añadir un elemento" y poder ingresar una linea de pago.

**Comment by jjscarafia** [comment]
Gracias por el reporte de error, tengo entendido que algo parecido pasaba al llegar desde tareas u otro lugar. Vamos a tratar de ver que puede ser. Igualmente bienvenido un PR con el arreglo
