### ISSUE TITLE
Soporte para 9.0 para account_check

### ISSUE THREAD

**Issue by ovnicraft** [ingadhoc/account-payment#15]
Trabajamos con este módulo, tiene algún plan para soportar 9.0 ?

de no hacerlo podemos hacer la migración.

Escribo aca para no duplicar esfuerzos.

**Comment by jjscarafia** [comment]
Buenas Cristian, justo estamos empezando a trabajar en esto y estabamos aprovechando a pensar si habría posibilidades de refactorizarlo y hacer algo más simple.
Viene de la mano de implementar "múltiples medios de pago". Si te parece podemos hacer un hangout para compartir puntos de vista (jjs@adhoc.com.ar)
Saludos,
Juan
