### ISSUE TITLE
En validación de pagos con clase account.payment.group

### ISSUE THREAD

**Issue by gbhadolfo** [ingadhoc/account-payment#167]
Hola, sugiero en la  funcion def _get_receiptbook(self) del archivo /account_payment_group_document/models/account_payment_group.py

hacer un raise validation, porque sino el error que tira no es posible rastrearlo facilmente:  "Error while validating constraint"

Sugiero agregar la siguiente línea antes del return:         i

if len(receiptbook)==0: raise ValidationError(_('No hay cargado un talonario de recibo'))

Abajo el código de la función: 

    @api.multi
    def _get_receiptbook(self):
        self.ensure_one()
        partner_type = self.partner_type or self._context.get(
            'partner_type', self._context.get('default_partner_type', False))
        receiptbook = self.env[
            'account.payment.receiptbook'].search([
                ('partner_type', '=', partner_type),
                ('company_id', '=', self.company_id.id),
            ], limit=1)

        if len(receiptbook)==0: raise ValidationError(_('No hay cargado un talonario de recibo'))
        return receiptbook

**Comment by jjscarafia** [comment]
Buenas @gbhadolfo . Gracias por el reporte. Podrías pasar pasos para replicar on un video? Porque si no hay talonarios en realidad no puedo guardar porque el campo es obligatorio en la vista. Sinceramente no encontré como llegar al error "Error while validating constraint"

Saludos!
