### ISSUE TITLE
[13] Calcula mal la deuda seleccionada al hacer un pago a proveedor

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/account-payment#189]
**Pasos para reproducir:**
En una base limpia se crea una factura de proveedor de $1000, y una nota de credito de proveedor por $400

Si se dejan sin conciliar, al hacer un pago de proveedor la deuda seleccionada es cero, deberia ser $600

Si se concilian la factura con la nota de credito, al hacer un pago de proveedor la deuda seleccionada es $1400, deberia ser $600

Nota: En recibos de cliente funciona correctamente.

**Comment by sotolucas** [comment]
Hola Jorge, gracias por reportar el issue.
Lo vamos a evaluar y te mantendremos actualizado.

**Comment by jjscarafia** [comment]
Buenas @jobiols ! La verdad es que no lo pude replicar. Lo pudiste replicar vos recientemente?

**Comment by jobiols** [comment]
@jjscarafia Estoy con algunos problemas, aguantame hasta manana y lo vuelvo a revisar.

**Comment by jobiols** [comment]
Hola @jjscarafia , acabo de revisar el issue, la primera parte ya no falla pero la segunda si
Te lo hago mas detallado:

**Repositorios instalados**
 https://github.com/ingadhoc/account-payment.git
 https://github.com/ingadhoc/account-financial-tools.git

Version Odoo: Odoo **13.0-20200407 (Versión Community)**

1. Creo base de datos nueva, Spanish / Argentina / sin demo.
2. Instalo modulo account_check, se instala todo sin errores ni warnings
3. Defino paquete de contabilidad para RI
4. Creo factura de proveedor por un total de $1000 iva No Gravado
5. Creo una factura rectificativa por $400 iva no Gravado
6. Concilio factura con NC dentro de la NC
7. Creo pago de proveedor.

Deuda seleccionada = $1400, Debería ser $600

Saludos !

**Comment by jjscarafia** [comment]
buenas @jobiols perdón la demora en ver esto, estuve a mil.
Ahí estaría resuelto con este [PR](https://github.com/ingadhoc/account-payment/pull/198). Gracias por el muy buen detalle para replicar.
Es un error del ORM me pinta pero con este parche se arregla. El tema es que al ejecutar el onchange y cambiar un m2m, las lineas que se agregan se crean como "new ids" y luego en vez de traer el residual almacenado en base de datos recomputa los residuals pero como son new lo hace mal.

**Comment by rhe-mastercore** [comment]
Hola que tal @jjscarafia, sabes que en la función **_compute_selected_debt** sigue llegando el computo del field line.amount_residual erróneo y como resultado **to_pay_amount** sigue dando un numero incorrecto, cuando revise lo que trae **amount_residual** el problema es que sigue llegando en dicha función los "news ids", slds crack!

**Comment by rhe-mastercore** [comment]
Que tal @jjscarafia, resolví el problema modificando en la función **_compute_selected_debt** de account_payment_group, la linea  **selected_debt += line.amount_residual** por **selected_debt += line.move_id.amount_residual** y tuve que cambiar también la variable sign por esto: **sign = 1.0** si deseas ver el cambio en nuestro repo esta [aca](https://github.com/odoo-mastercore/odoo-argentina/commit/79916d6d2e681c0340901924c025f0d456a6b576) y [aca](https://github.com/odoo-mastercore/odoo-argentina/commit/485c713420392d7cb7ad99870e6ce68062864e78), valida si esa es la forma correcta, espero tus comentarios slds!

**Comment by jjscarafia** [comment]
Buenas @rhe-mastercore Gracias por el reportar el error y pasar propuesta de solución. Lo resolví [así](https://github.com/ingadhoc/account-payment/pull/201) que creo que iría mejor, cualquier cosa decime

**Comment by rhe-mastercore** [comment]
@jjscarafia Para que lo reviso, de entrada te comento que ese field _origin no lo vi, no tuviste que cambiar el sing? Por allí cambio mi solución por la tuya lo reviso y te comento, gracias a vos por atenderlo, sldls crack!
