### ISSUE TITLE
[11.0] Calcular Retenciones en Pago a proveedores.

### ISSUE THREAD

**Issue by sebatista** [ingadhoc/account-payment#193]
Hola, Estamos utilizando el módulo de retenciones en la versión de Odoo 11.0.
Hemos configurado un diario de la siguiente manera:
![image](https://user-images.githubusercontent.com/27778036/79797998-aa78d000-832e-11ea-92ff-c56ce395c940.png)
![image](https://user-images.githubusercontent.com/27778036/79798063-c67c7180-832e-11ea-9b9d-ae233041efde.png)

Además configuramos el impuesto para Retención Aplicada de la siguiente manera:
![image](https://user-images.githubusercontent.com/27778036/79798572-984b6180-832f-11ea-82dd-4e696b03765a.png)

y
![image](https://user-images.githubusercontent.com/27778036/79798699-bb761100-832f-11ea-9363-5a18651cd7ec.png)

Pero al momento de registrar un pago a proveedores, para un proveedor de Buenos aires, situación RI, y nosotros siendo situación RI y convenio multilateral, no descarga las alícuotas de IIBB del partner. 
Si lo hace al registrar una factura del proveedor, pero de todas formas no utiliza esas alícuotas descargadas.
El funcionamiento esperado sería el inverso, en la factura una carga manual de la percepción sufrida y en el pago al proveedor un calculo en base a la alícuota de la Retención aplicada.
![image](https://user-images.githubusercontent.com/27778036/79799312-a2219480-8330-11ea-9e41-67b5505c86e4.png)

Cual puede ser la causa? falta configurar algún punto?

**Comment by jjscarafia** [comment]
Cierro por inactividad
