### ISSUE TITLE
[13.0] Problema al intentar pagar un monto parcial. 

### ISSUE THREAD

**Issue by rhe-mastercore** [ingadhoc/account-payment#203]
Si intento pagar el monto parcial de una factura me arroja el siguiente error:
**AttributeError: 'account.move.line' object has no attribute 'invoice_id'**

para solucionarlo cambien en la función **_get_withholdable_amounts** del archivo **account_payment_group** del modulo **account_withholding_automatic** la linea de código **partial_line.invoice_id:** por **partial_line.move_id:**
Revisen si el cambio esta bien formulado por favor y gracias, slds.

**Comment by jjscarafia** [comment]
Cierro por inactividad
