### ISSUE TITLE
Al cancelar un pago de una factura con account_payment_group, no cancela el asiento del pago

### ISSUE THREAD

**Issue by gbhadolfo** [ingadhoc/account-payment#227]
Buen día, en versión 13 CE, al cancelar un pago de una factura desde el módulo account_payment_group, no cancela el asiento del pago

Lo que ocurre: Cancela el payment group, los pagos, pero no los asientos de pago, borra las líneas conciliadas.

Lo que debería ocurrir: Que cancele el/los asiento/s de pago para que no figuren en la contabilidad.

Yo lo solucioné agregando esta línea en el procedimiento def cancel(self) de account_payment_group/models/account_payment_group.py: move.write({'state': 'cancel'})

**Comment by PabloPaezSheridan** [comment]
Hola Adolfo, estuve intentado replicarlo y no pude ver que los asientos no se hagan correctamente, podes mandarnos un video o los pasos bien claros para ver como llegaste al error? disculpa la demora en la respuesta
