### ISSUE TITLE
[13.0] account_check

### ISSUE THREAD

**Issue by esakarya** [ingadhoc/account-payment#241]
When do you plan to complete the to-do in the account_check module?

**Comment by jjscarafia** [comment]
Hi @esakarya 
Which TODO's do you mean?
We don't have new features in mind

**Comment by esakarya** [comment]
can use now production ?

**Comment by jjscarafia** [comment]
yes. We're using v13 in production with 100 customers since 6 months

**Comment by esakarya** [comment]
i will begin use but i dont want use payment_group. i saw manifest,py.

TODO we should move field amount_company_currency to
account_payment_fix so that we dont need to depend
any quick way fix this ?
