### ISSUE TITLE
[15] Problema con la numeración de las transferencias internas

### ISSUE THREAD

**Issue by juanpgarza** [ingadhoc/account-payment#281]
Buenas gente.

Estoy teniendo un problema con la numeración de las transferencias internas entre diarios (opción de menú Contabilidad / Bank and Cash / Transferencias). 
Me está tomando la numeración de los talonarios de recibos que utiliza account.payment.group
En Odoo v12/13 las transferencias internas tenían su propia numeración.
Es v15 enterprise y este comportamiento que describo lo reproduje en esta db del runbot 19509-15-0-all.runbot.adhoc.com.ar
con un ejemplo de un depósito de cheques de tercero. Les dejo una captura de pantalla:

![image](https://user-images.githubusercontent.com/41624203/169917936-715d3339-d73c-4d83-97cc-246e6735d30f.png)

**Comment by juanpgarza** [comment]
@jjscarafia

**Comment by jjscarafia** [comment]
gracias @juanpgarza 
le voy  a pegar un vistazo

**Comment by jjscarafia** [comment]
buenas @juanpgarza 
esto debería estar resuelto acá https://github.com/ingadhoc/account-payment/pull/290

**Comment by juanpgarza** [comment]
buenas @jjscarafia . Perfecto!
lo pruebo y cualquier cosa te comento.
Gracias!
