### ISSUE TITLE
[15] Where is gone account_check ?

### ISSUE THREAD

**Issue by esakarya** [ingadhoc/account-payment#283]
[15] Where is gone account_check module ? what can i use for it ?

**Comment by juanpgarza** [comment]
Para v15 podes usar l10n_latam_check (lo podes encontrar en este mismo repo). Este módulo lo está desarrollando adhoc para Odoo y va a ser próximamente incluido dentro del CORE community.

**Comment by jjscarafia** [comment]
Hi @esakarya 
We are working on adding checks management to odoo https://github.com/odoo/odoo/pull/83542
In the menatime, the content of the PR is copy pasted to this repository as l10n_latam_check module
