### ISSUE TITLE
[IMP][9.0] Usar modelo account.payment para implementar account.payment.group

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/account-payment#29]
La propuesta es que el módulo account_payment_group, en vez de generar un nuevo modelo "account.payment.group" implemente toda esa lógica en account.payment agregando un nuevo tipo de pago (payment_type = group). Básicamente quedarían payments con payments hijos

Notas de desarrollo:

- Hacer journal_id no required

Ventajas:

- No haría falta ocultar y generar nuevos menus, si cambiaríamos el dominio de los menus para que se muestren los payments que no tengan payment padre
- La integración con account_document sería más directa, ya que es la misma clase la que tendría el tipo de documento y la numeración
- Si se instala el módulo en una bd con datos, no habría que generar un payment group para cada payment actual ya que se podrían visualizar y consultar sin problemas
- La migración de datos parece que iría más facil entre v8 y v9 (por mismo tema de punto anterior)
- No recuerdo ahora pero había algunas otras que había pensado

No muy lindo:

- Deberíamos hacer que journal_id sea no requerido (no muy odoo way)
- Si se desinstala el módulo habría que proponer borrar todos los payments del tipo group o algo por el estilo

**Comment by ivantodorovich** [comment]
Hola Juan,

La verdad que me gusta más como está ahora. Justamente cuando lo vi, me llamó la atención lo prolijo que es, conceptualmente. Un `account.payment.group` es una Orden de Pago que agrupa uno o más pagos. No hay nada mas para decir, es simple, y funciona "por arriba" de la implementación nativa de Odoo.

Implementar el payment.group dentro del mismo payment creo que complicaría las cosas, al menos a nivel conceptual.

Sin embargo, para poder opinar mejor, debería conocer cuáles son los problemas con la implementación actual. Si no hubiera problemas, te diría que lo dejes como está.. pero ahí mencionás algún tipo de inconveniente con `account_document`. Las otras ventajas son debatibles.

**Comment by jjscarafia** [comment]
La idea sería que conceptualmente funcione igual que ahora pero que la clase agrupadora pueda ser la misma clase, otras ventajas que se me ocurren:

* ahora mismo como está implementado deberíamos crear un menú para las transferencias (ya que son account.payment) que no llevarían un payment.group por arriba, igualmente esto no lo veo tan feo
* Actualmente, los kanban de journals te permiten navegar y llegar a los payments. No podría ser confuso eso?
* Por las dudas deberíamos bloquear la creación de cualquier payment sin payment group salvo para los payments "transfer". Porque si se crea alguno va a quedar inaccesible

Estoy casi seguro que había pensado en otra pero me quedé dormido jeje. Ahora que escribo estas tres en realidad me parece que son mejoras pero son cosas que podemos resolver usando una clase distinta tmb. No me termino de definir....

**Comment by ivantodorovich** [comment]
Ok @jjscarafia !!

Realmente no creo que pueda opinar demasiado, ya que no estoy tan empapado del tema como vos.
Pero si te ayuda a aclarar tus ideas, te respondo por puntos:

> - ahora mismo como está implementado deberíamos crear un menú para las transferencias (ya que son account.payment) que no llevarían un payment.group por arriba, igualmente esto no lo veo tan feo

De cualquier manera yo agregaría este menú. Para el usuario, una transferencia y un pago son cosas distintas.. más allá de que internamente sean lo mismo.

--- 

> - Actualmente, los kanban de journals te permiten navegar y llegar a los payments. No podría ser confuso eso?

Es cierto, eso puede llegar a ser confuso..  

Sin embargo, ¿No sería el resultado similar con la propuesta de payments del tipo 'group', ya que estos no tienen diario? Al no tener diario, no serían listados al hacer click desde el kanban, mostrando únicamente los payments "normales". ¿Cómo sería menos confuso eso?

La "lógica" que le encuentro es cuando pienso en los pagos como pequeños movimientos dentro de una orden de pago. Y con eso en mente, tal vez la solución sea no intentar ocultar el menú original, sino más bien agregar uno nuevo y que convivan los dos. 

Similar a como conviven los menúes nativos 'Elementos del Diario', que muestra las líneas de 'Asientos contables'.

--- 

> - Por las dudas deberíamos bloquear la creación de cualquier payment sin payment group salvo para los payments "transfer". Porque si se crea alguno va a quedar inaccesible

Comparto, pero sólo si se va por el camino de ocultar el menú original.

**Comment by jjscarafia** [comment]
Bárbaro, ya estuvimos hablando acá tmb y nos quedamos con el diseño actual. Cierro esta incidencia. Te paso un resumen de lo que hicimos:
1. nuevo menu para transferencias
2. bloqueamos creación de payments sin payment group
3. igualmente se pueden acceder a los payments desde el dashboard contable
4. ocultamos los menus de pagos pero se pueden agregar con un grupo de permisos a tal fin

Creo que eso sería todos
