### ISSUE TITLE
[9.0][account_payment_group] Agregar herencia a `mail.thread`

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-payment#30]
Y supongo que con eso se puede hacer uso del botón Enviar por Mail, que actualmente tira el siguiente error:

```
AttributeError: 'account.payment.group' object has no attribute 'message_get_reply_to'
```

**Comment by jjscarafia** [comment]
Hecho en https://github.com/ingadhoc/account-payment/pull/38
