### ISSUE TITLE
[9.0][account_payment_group] El botón [+ Nota de Débito] y [+ Nota de Crédito] no funciona con la localización argentina

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-payment#31]
![unnamed](https://cloud.githubusercontent.com/assets/1914185/20991062/f44b5114-bcba-11e6-9128-4f433112cd4b.png)

Comentarios por @jjscarafia : 

>Hay otro tema relativo a esto que es que una vez validado el pago no queda vínculo de que esa nota de débito se generó desde ese pago. 
>
>Si es necesario, dicho link podría ser:
>1. Simplemente el campo origen de la factura que tenga de manera descriptiva ese dato
>2. Si es necesario, además agregar un campo función en los payment groups que busque comprobantes con origen igual a código de pago y los muestre con un m2m computado 
>3. agregar un campo m2o en facturas que sea "origin_payment_id" y si es necesario campo inverso o2m en pagos
>4. agregar un campo m2m en pagos y/o facturas generadas

**Comment by jjscarafia** [comment]
Resuelto lo que reportaste acá https://github.com/ingadhoc/account-payment/pull/38
