### ISSUE TITLE
[9.0][account_payment_group] Agregar grupo para ocultar el campo "payment_type_copy" (Tipo de Pago) en account.payment, al ser creado desde un payment.group

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-payment#32]
El hecho de que se pueda "Enviar Dinero" en una Orden de Pago de Cliente (Recibos) es ilógico, y resulta confuso y posiblemente problemático.
Creo que sería mejor ocultar ese campo, y dejar que se setee automáticamente dependiendo de si estamos en una Orden de Pago de Cliente o de Proveedor.

![unnamed 1](https://cloud.githubusercontent.com/assets/1914185/20991157/a16f6f9c-bcbb-11e6-9c04-2ec20ae0430a.png)

---

@jjscarafia:
>estos campos los dejé por si querías hacer un ajuste, por ejemplo, te pagan con un cheque de $1500 y le devolves $50 en efectivo. Básicamente fue permitir que un payment group pueda tener pagos para ambos lados y lo que importa es la suma. De última lo podemos ocultar o no con un grupo y opción de configuración, pero conceptualmente me parece que es correcto no limitarlo, de hecho originalmente lo había hecho como decis, el payment_type estaba en payment.group y defínia los payment_type de los pagos

**Comment by ivantodorovich** [comment]
Creo que sería bueno ocultarlo detrás de un grupo de seguridad. 
Nunca me ha ocurrido tener que hacer una operación como la que comentas. Es un comportamiento no muy tradicional, y puede resultar confuso.

**Comment by jjscarafia** [comment]
Bárbaro, lo agarro yo

**Comment by jjscarafia** [comment]
Hecho en https://github.com/ingadhoc/account-payment/pull/38
