### ISSUE TITLE
[9.0][account_payment_group] Permitir elegir, en account.payment, una fecha distinta a la del account.payment.group

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-payment#33]
Sería particularmente útil para registrar una Orden de Pago de un cliente compuesta por varios comprobantes de depósitos bancarios, realizados en distintas fechas.

**Por ejemplo:**

Cliente X nos informa que canceló la factura de $ 15.000 de la siguiente manera:

Fecha | Detalle
--- | ---
15/08 | Depósito de $ 5000 en CC Galicia
16/08 | Depósito de $ 5000 en CC Galicia
20/08 | Entrega efectivo por $ 5000

Nosotros registramos la Orden de Pago el 20/08, ingresando las 3 líneas de pagos tal cual las informa el cliente (de acuerdo a sus comprobantes de transferencia/depósito)

De esa manera, se guardan las fechas de los depósitos, y eso agiliza muchísimo el trabajo de realizar conciliaciones bancarias, ya que las líneas de Pagos coinciden en fecha e importe con las líneas en el resumen bancario.

Notas:
El valor podría dejarse vacío y luego completarse con la fecha del payment.group, si no está definido.

**Comment by jjscarafia** [comment]
Me parece bárbaro, lo podrás agarrar vos con un PR? Cualquier cosa decime

**Comment by jjscarafia** [comment]
Hecho en https://github.com/ingadhoc/account-payment/pull/38

**Comment by jjscarafia** [comment]
Aproveché y lo agarré yo ya que estaba haciendo lo otro..
