### ISSUE TITLE
[9.0][account_payment_group] ¿Cómo mejorar la usabilidad de pagos con Cheques y/o retenciones?

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-payment#34]
El hecho de que cada cheque sea un payment del tipo Efectivo, y se deba seleccionar tipo de pago a "Received Third Check" antes de cargar los datos del cheque hace que ya no se pueda cargar una serie de cheques tan fácilmente con el botón "Guardar y Nuevo".

Mi sugerencia es que, por cuestiones de usabilidad:

Se agregue una solapa "Cheques" y otra "Retenciones" en account.payment.group, al lado de Lineas del Pago, algo así:
![unnamed 2](https://cloud.githubusercontent.com/assets/1914185/20991469/6ac5c372-bcbd-11e6-8ecc-822d79718ba6.png)

Internamente, el funcionamiento podría ser similar a lo que es ahora.. es decir, cada cheque podría ser un account.payment, sólo que modificaríamos la vista para no solicitar el "Tipo de Pago" (ya que sería cheque o retención, seleccionado automáticamente)

**Comment by ivantodorovich** [comment]
@jjscarafia:

>La verdad es que no preferiría hacer dichos cambios ya que agregaríamos dependencia de cheques y retenciones al payment group y además recargaríamos con funcionalidad, filtros y demás. 
>
>O sea, si podemos mejorarlo de otra manera la verdad lo prefiero. 
>
>(...)
>
>Otras alternativas para mejorarlo:
>1. Hacer que un account.payment pueda tener varios cheques: en realidad era antes así (account.payment es análogo a account.voucher), pero la verdad me pareció más prolijo esta forma actual, además para que permita tener varios habría que sobreescribir el método original de account.payment para generar el asiento ya que no es heredable para poder generar varios apuntes (uno por cada cheque)
>
>2. Si el guardar y nuevo puede pasar por contexto de alguna manera lo que tenías seleccionado, por ahí se puede lograr que vuelva a elegir el mismo método de pago y diario (aunque en realidad no sería el uso más común además)
>
>3. De última, si llega a ser supr necesario, se puede implementar esto que decís con un módulo por arriba de account_payment_group, cheques y retenciones que cambie el uso a como lo propones

**Comment by ivantodorovich** [comment]
A la hora de la sugerencia, estaba pensando, de hecho, en la opción número 3: 
Agregar módulos "glue" `account_payment_group_check` y `account_payment_group_withholding`.
Serían módulos simples con el único fin de mejorar la usabilidad, y serían auto-instalables.

Comparto la opinión de que es más prolijo un cheque por cada `account.payment`.

**Comment by jjscarafia** [comment]
Perfecto, me parece bien, te quedas con esta, ok?ç
Alternativas de nombres:

- Hacemos dos módulos llamados account_payment_group_check y account_payment_group_withholding
- Un módulo account_payment_group_extended

Alguna otra? Como te parece?

NOTA: el código de account.payment.group está muy sucio, ya lo voy a limpiar, lo dejé así porque todavía es una beta y me sirve tener código viejo por ahí hasta que se va depurando un poco

**Comment by ivantodorovich** [comment]
Ok @jjscarafia !

Perdón por demorarme en contestar. Subestimé mi agenda para estos últimos días del año, y todavía no pude ponerme con esto. Pero en breve lo haré!
