### ISSUE TITLE
[9.0][account_check] ¿Se deprecó a propósito el menú de Cheques?

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-payment#35]
Veo que en 9.0 la única forma de acceder al listado de cheques es a través del tablero, ya que no existe el menú _Cheques de Terceros_ ni _Cheques Propios_.

Mi sugerencia es mantener los menúes tal cual estaban. Está bueno el indicador del tablero, pero no creo que sea suficiente. Creo que es práctico poder acceder desde el menú también.

De hecho, si bien Odoo agregó el link a las facturas del diario, no eliminó el menú de facturas de cliente.

**Comment by jjscarafia** [comment]
SI, la eliminación fue para tratar de mantenernos más cerca de la nueva odoo way de usar dashboard y, por ejemplo, eliminar el menú de reembolsos, extractos bancarios y demás. Tmb me parece que va a ser útil agregarlo, no lo haría ya, me gustaría dar una oportunidad a ver si puede no estar. De ser necesario se agrega de manera muy simple.

**Comment by jjscarafia** [comment]
Lo volvimos a agregar en este pr https://github.com/ingadhoc/account-payment/pull/43
