### ISSUE TITLE
[9.0][account_check] Estado "Anulado" en cheques

### ISSUE THREAD

**Issue by gustavovalverde** [ingadhoc/account-payment#37]
El módulo de cheques me parece muy interesante, pero siempre me ha extrañado que tanto en el core como en módulos de terceros no se considere un estado "Anulado" en el cheque. 

Ya sea por error de impresión, digitación u otro. Un cheque impreso o emitido puede ser luego anulado. Actualmente Odoo no tiene este estado, y cuando un cheque se cancela pasa nuevamente a Draft y las entradas de Diario **desaparecen**.

Sería muy práctico agregar a este módulo un estado de "Anulado" o "Cancelado", y revertir los Apuntes Contables con este estado (al igual que con una factura).

**Comment by jjscarafia** [comment]
gracias @gustavovalverde . 
En la v8 teníamos algo así, ahora lo agrego a la v9, sería simple me parece

**Comment by jjscarafia** [comment]
mmm, en realidad ahora que veo no es tan simple. En la v9 odoo eliminó el estado cancelado en account.payment por lo cual no se me ocurre una manera prolija de implementar esto a cheques. Si se puede registrar un cheque y cargar una operación de que esté cancelado de manera manual.

**Comment by gustavovalverde** [comment]
> mmm, en realidad ahora que veo no es tan simple. En la v9 odoo eliminó el estado cancelado en account.payment

Yo aún entiendo porqué hicieron eso.

Quisiera ver si te ayudo con el tema, me refieres a la parte del código de la V8 dónde hiciste esa adaptación? (Yo no tengo mucha experiencia programando, pero posible consigo alguien que nos de una mano con eso).
