### ISSUE TITLE
V16 account_payment_group Error al cerrar POS usando diferentes metodos de pago.

### ISSUE THREAD

**Issue by trixocom** [ingadhoc/account-payment#401]
Arroja este mensaje
"Manual payments should not be created manually but created from Customer Receipts / Supplier Payments menus"
La sesion queda sin poder cerrarse.
Desinstalando account_payment_group se soluciona.
Ver que pasa, ya que evita poder usar muchas funcionalidades en V16 EE se pierden sin usar ese modulo.

Gracias.

**Comment by maq-adhoc** [comment]
@trixocom están mal configurados los métodos de pago en el pos.

**Comment by trixocom** [comment]
Si si lo resolvimos en su momento, olvide cerrar el ticket. Gracias!
