### ISSUE TITLE
Account_Payment_Group

### ISSUE THREAD

**Issue by gomezgleonardob** [ingadhoc/account-payment#421]
Saludos, se va a mantener esté módulo como dependecia para **account_cashbox**, me interesa colaborar en la migración

**Comment by maq-adhoc** [comment]
Hola @gomezgleonardob , Diculpa no vi este issue, account cashbox esta ya migrado https://github.com/ingadhoc/account-payment/commits/17.0/account_cashbox .
SI queres deseas colaborar los tests y PRS siempre son bienvenidos.
