### ISSUE TITLE
When brunch for Odoo 10 version?

### ISSUE THREAD

**Issue by mdemirell** [ingadhoc/account-payment#44]
If you do it would be great, 10.0 brunch for Odoo 10 version?

**Comment by salvatoretrimarchi** [comment]
@mdemirell we work about Odoo 10 fork ingadhoc Odoo 9 https://github.com/bacgroup/account-payment

**Comment by jjscarafia** [comment]
We look forward to do it on july 2017.

**Comment by jjscarafia** [comment]
Branch already created.
Thanks!
