### ISSUE TITLE
Payline currency calculation problem

### ISSUE THREAD

**Issue by levkar** [ingadhoc/account-payment#48]
Hello,

account_voucher_payline is not taking currency on the voucher into account and generates a difference move line.

Scenario: When receiving EUR payment, at the bottom select local currency and set a custom rate. An extra move line is being created when confirmed.

As far as I understood, paid_amount_in_company_currency should be used instead of _convert_amount in net amount but what to do with account_check and account_voucher_withholding ?

Solution might be moving calculation of amount to calling functions?

**Comment by jjscarafia** [comment]
Hi and thanks for reporting. I'm sorry but we are moving to v9 and this module has been completely redesigned. We are not going to work or introduce changes if our customers don't report them.
Once again, sorry!

**Comment by levkar** [comment]
thanks!
