### ISSUE TITLE
account_payment_fix genera un error al intentar hacer transferncias internas

### ISSUE THREAD

**Issue by angra1982** [ingadhoc/account-payment#53]
Cuando está instalado, las transferencias internas no funcionan. Aparece como método de pago "Unknown" solamente y no se puede elegir el banco destino. 
![captura de pantalla 2017-06-18 a las 6 17 04 p m](https://user-images.githubusercontent.com/4574090/27264328-780d787c-5452-11e7-82f3-1df41d17925d.png)
![captura de pantalla 2017-06-18 a las 6 17 00 p m](https://user-images.githubusercontent.com/4574090/27264329-7b660d40-5452-11e7-86ae-13bff98a5083.png)
al desinstalarlo vuelve a funcionar correctamente

**Comment by angra1982** [comment]
al desinstalarlo vuelve a funcionar correctamente.

**Comment by jjscarafia** [comment]
Buenas, probablemente se deba a todo lo que se hablá [acá](https://github.com/ingadhoc/odoo-argentina/issues/188), es un mismo issue, tiene que ver con un cambio en odoo en marzo 2017 que hizo que los dominios por vista usando campos m2m (tipo "in", "journal_ids[0][2]") dejen de funcionar.

Por ahora nosotros venimos trabajando con una versión anterior donde todavía funciona

**Comment by jjscarafia** [comment]
Cierro por duplicado, si llega a ser otra cosa, por favor re-abrir
