### ISSUE TITLE
Método de pago vacío en Ventas/Compras Pagos

### ISSUE THREAD

**Issue by sarriaroman** [ingadhoc/account-payment#56]
Al intentar generar un Pago no aparecen los Métodos de Pago. Sólo se puede marcar como paga desde la factura. Lo esperado sería que se pueda hacer pagos parciales.

Comentarios:
- Según lo buscado hay cambios recientes en Odoo 9 en Marzo que cambian el comportamiento en la búsqueda aunque para el pago de factura que fue lo reportado funcionan correctamente.
- No se puede reproducir en Runbot debido a que no está al módulo.

Version affectada:
9.0 ( 20170701 )

Pasos para reproducir:

Nueva instalación con Docker
- Plan Contable Generico Argentina para Responsables Inscriptos

1) Generar una Factura
2) Ir al menú Ventas -> Pagos
3) Elegir el Cliente
4) Tipo de Pago: Recibir Dinero
5) Método de pago está vacío.

Lo que debe pasar:

Se deberían poder cargar pagos parciales.

Ambiente: Docker
- Imagen: adhoc/odoo-ar:9.0
- Versión: 9.0c-20170701

Módulos:
- account_payment_fix: 9.0.1.0.0

Otros Datos
- Instancia basada en Docker
- Únicos módulos: Contabilidad y Facturación
- Plan Contable: Plan Contable Generico Argentina para Responsables Inscriptos

Screenshots: 
- https://drive.google.com/file/d/0B429dbdUsK_tNURhend3b0NweUU/view?usp=sharing
- https://drive.google.com/file/d/0B429dbdUsK_tNkprWUdBazVqelU/view?usp=sharing

**Comment by jjscarafia** [comment]
Buenas, según veo es issue duplicado a [este](https://github.com/ingadhoc/odoo-argentina/issues/188) registrado en odoo argentina, puede ser que sea eso mismo?

**Comment by sarriaroman** [comment]
@jjscarafia ese caso planteado en el issue que mencionas a mi me funciona correctamente, el caso que no me funciona es para cargar pagos parciales que es donde justamente no me aparecen las Cuentas para cargar. El issue no es el mismo pero parece venir por el mismo lugar según lo que veo en el hilo, el tema es por qué en un caso anda y el otro no, es lo que no logro encontrar.

**Comment by sarriaroman** [comment]
Cierro el issue, el problema se soluciona al instalar el módulo "Customer Debt Management". Ahora si tengo el otro issue y tengo que ver cómo resolverlo dentro del docker.
