### ISSUE TITLE
Funcionalidad modulo account_check

### ISSUE THREAD

**Issue by jobiols** [ingadhoc/account-payment#6]
Si se hace un pago desde una factura con método de pago cheque, el sistema propone como monto a pagar el total de la factura, entonces sale un aviso diciendo:

> You can not use a check journal with Net Amount different from 0. Correct it first

No queda claro para el usuario que es lo que tiene que hacer, para continuar el proceso hay que poner el monto en cero.  En algún momento se forzaba a cero según pude ver aquí account_voucher.py [153]

```
    def _get_checks_amount(self):
        # Hack because sometimes net_amount is not 0 and then we have an error
        # we delete this hack because now we check net amount = 0 on checks
        # journals
        # self.net_amount = 0.0
```

Sería mejor que se fuerce el monto a cero desde el programa como se hacía antes.

**Comment by jjscarafia** [comment]
Esto debería estar resuelto o al menos no se presenta más en la v9, lo cerramos
